config/routes.rb
Rails.application.routes.draw do
  # create routes only for create and new
  resources :posts, only: %i[create new] do
    # define additional routes nested under the posts resource.
    resources :comments, only: %i[create new]
    resources :likes, only: :create do
      collection do
        delete :destroy
      end
    end
  end
  devise_for :users, controllers: { registrations: "registrations" }
  resources :conversations do
    resources :messages
  end
  # define a custom route for the "/users" path
  resources :users, only: %i[index show] do
    resources :friendships, only: :create do
  # we use the collection block to define a set of routes
  # that operate on the collection of resources as a whole.
  # In this case, we're defining a delete route
  # that will operate on all friendships, not just a specific one.
      collection do
        delete :destroy
      end
    end
  end
  root 'site#index', as: :sites
#   get "*path", to: "errors#not_found", constraints: lambda { |req|
#   !req.path.start_with?("/rails/active_storage")
# }
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
  validates :user_id, uniqueness: { scope: :friend_id }
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :require_login
  def create
    @user = User.find(params[:friend_id])
    current_user.follow!(@user)
  end

  def destroy
    @user = User.find(params[:friend_id])
    current_user.unfollow!(@user)
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
  def send_notification_to_friends(user, post)
    friend_ids = Friendship.where(user_id: user.id).pluck(:friend_id)
    User.where(id: friend_ids).each do |friend|
      NewsMailer.notification(friend, post).deliver_later
    end
  end
end

app/views/friendships/utils/_follow_buttons.html.erb
<% if user_signed_in?  %>
  <% if user.friendships.where(friend_id: current_user.id).exists? %>
    <%= button_to "Unfollow", user_friendships_path(user_id: current_user.id, friend_id: user.id), method: :delete, class: "btn btn-danger btn-rounded btn-lg" %>
  <% else %>
    <%= button_to "Follow", user_friendships_path(user_id: current_user.id, friend_id: user.id),method: :post, class: "btn btn-success btn-rounded btn-lg" %>
  <% end %>
<% end %>