config/routes.rb
Rails.application.routes.draw do
  # create routes only for create and new
  resources :posts, only: %i[create new] do
    # define additional routes nested under the posts resource.
    resources :comments, only: %i[create new]
    resources :likes, only: :create do
      collection do
        delete :destroy
      end
    end
  end
  devise_for :users, controllers: { registrations: "registrations" }
  resources :conversations do
    resources :messages
  end
  # define a custom route for the "/users" path
  resources :users, only: %i[index show] do
    resources :friendships, only: :create do
  # we use the collection block to define a set of routes
  # that operate on the collection of resources as a whole.
  # In this case, we're defining a delete route
  # that will operate on all friendships, not just a specific one.
      collection do
        delete :destroy
      end
    end
  end
  root 'site#index', as: :sites
#   get "*path", to: "errors#not_found", constraints: lambda { |req|
#   !req.path.start_with?("/rails/active_storage")
# }
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, foreign_key: :sender_id, class_name: 'User'
  belongs_to :receiver, foreign_key: :receiver_id, class_name: 'User'
  has_many :messages, dependent: :destroy
  validates :sender, uniqueness: { scope: :receiver }

  def self.between(user1_id, user2_id)
    where(sender_id: user1_id, receiver_id: user2_id).or(where(sender_id: user2_id, receiver_id: user1_id)).first
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!
  before_action :initialize_new_conversation, only: [:show]

  def index
    @user = User.find(receiver_params)
    @conversations = current_user.conversations.order(created_at: :desc)
  end

  def show
    @conversation = Conversation.between(current_user.id, params[:receiver])
    @messages = Message.where(conversation_id: @conversation.id)
  end

  def create
    @conversation = Conversation.between(current_user.id, receiver_params)

    unless @conversation.present?
      @conversation = Conversation.create(sender_id: current_user.id, receiver_id: receiver_params)
    end
    redirect_to conversation_path(id: @conversation, receiver: receiver_params)
  end

  private


  def initialize_new_conversation
    return if Conversation.between(current_user.id, params[:receiver]).present?

    redirect_to user_path(params[:receiver])
  end

  def receiver_params
    params.require(:id)
  end

end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_message.html.erb
<div id="chat-container" data-current-user-id="<%= current_user.id %>"></div>
<div id="message-container">
  <% messages.each do |message| %>
  <% if current_user.id != message.sender.id %>
  <div class="d-flex flex-row justify-content-start">
    <%= image_tag(message.sender.avatar.url, alt: 'avatar', class: "avatar-user") %>
    <div>
      <p class="small p-2 ms-3 mb-1 rounded-3" style="background-color: #f5f6f7;"><%= message.body %> </p>
    </div>
  </div>
  <% else %>
  <div class="d-flex flex-row justify-content-end mb-4 pt-1">
    <div>
      <p class="small p-2 me-3 mb-1 text-white rounded-3 bg-primary"><%= message.body%></p>
    </div>
    <%= image_tag(message.sender.avatar.url, alt: 'avatar', class: "avatar-user") %>
  </div>
  <% end %>
  <% end %>
</div>

app/views/conversations/index.html.erb
<h1>Conversations</h1>
<%= button_to "Start conversation with User 2", conversations_path(id: @user.id), method: :post %>

app/views/conversations/show.html.erb
<section style="background-color: #eee">
  <div class="container py-10">

    <div class="row d-flex justify-content-center">
      <div class="col-md-12 col-lg-12 col-xl-12">

        <div class="card">
          <div class="card-body" data-mdb-perfect-scrollbar="true" style="position: relative;height: 70vh;overflow-y: auto;">
            <%= render 'message', messages:@messages  %>
          </div>
          <div class="card-footer d-flex justify-content-center align-items-center ">
             <%= image_tag(current_user.avatar.url, alt: 'avatar', class: "avatar-user") %>
            <%= form_with model: @message,url:  conversation_messages_path(@conversation), class: "row g-10 d-flex justify-content-center" do |f| %>
             <%= f.hidden_field :conversation_id, value: @conversation.id %>
              <%= f.hidden_field :sender_id, value: current_user.id %>
            <div class="col-md-10">
              <%= f.text_field :body,input_html: {autofocus: true }, class: "form-control form-control-lg", placeholder: "Message", id: "message_input" %>
          </div>
             <div class="col-md-2">
             <%= f.submit :send, class: "btn btn-dark btn-lg" %>
             </div>
        <% end %>
          </div>


      </div>
    </div>

  </div>
</section>