config/routes.rb
Rails.application.routes.draw do
  # create routes only for create and new
  resources :posts, only: %i[create new] do
    # define additional routes nested under the posts resource.
    resources :comments, only: %i[create new]
    resources :likes, only: :create do
      collection do
        delete :destroy
      end
    end
  end
  devise_for :users, controllers: { registrations: "registrations" }
  resources :conversations do
    resources :messages
  end
  # define a custom route for the "/users" path
  resources :users, only: %i[index show] do
    resources :friendships, only: :create do
  # we use the collection block to define a set of routes
  # that operate on the collection of resources as a whole.
  # In this case, we're defining a delete route
  # that will operate on all friendships, not just a specific one.
      collection do
        delete :destroy
      end
    end
  end
  root 'site#index', as: :sites
#   get "*path", to: "errors#not_found", constraints: lambda { |req|
#   !req.path.start_with?("/rails/active_storage")
# }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/avatar.rb
class Avatar < ApplicationRecord
  has_many :users
end

app/models/comment.rb
#=> ID, user_id, post_id, body
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :body, presence: true,
                   length: { maximum: 500, minimum: 1 }
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, foreign_key: :sender_id, class_name: 'User'
  belongs_to :receiver, foreign_key: :receiver_id, class_name: 'User'
  has_many :messages, dependent: :destroy
  validates :sender, uniqueness: { scope: :receiver }

  def self.between(user1_id, user2_id)
    where(sender_id: user1_id, receiver_id: user2_id).or(where(sender_id: user2_id, receiver_id: user1_id)).first
  end
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
  validates :user_id, uniqueness: { scope: :friend_id }
end

app/models/like.rb
# user_id, post_id
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :sender, foreign_key: :sender_id, class_name: 'User'
end

app/models/post.rb
#=> ID, user_id, body
class Post < ApplicationRecord
  has_one_attached :image do |att|
    att.variant :thumb, resize_to_limit: [100, 100]
  end
  belongs_to :user
  validates :body, presence: true,
                   length: { maximum: 500, minimum: 1 }
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_one :avatar, through: :user
end

app/models/user.rb
# => id,email,password,username,avator,like(post),follow(user),comment(post)
class User < ApplicationRecord
  attr_accessor :current_password

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :likes
  has_many :comments
  belongs_to :avatar
  validates :username, presence: true
  # dependent: :destroy to the association,
  # which means that when a User is deleted,
  # all associated Conversations will be deleted as well.
  # This is usually the behavior you want for a dependent association.
  has_many :conversations, foreign_key: :sender_id, dependent: :destroy
  has_many :messages, through: :conversations
  # Define a many-to-many association with itself for friendships
  has_many :friendships, dependent: :destroy
  # define has_many :friends, through: :friendships, source: :friend,
  # you are telling Rails to look for the friend association
  # in the Friendship model, which is a join table between
  # two instances of the User model.
  # This allows you to access the friends of a user through the Friendship model.
  has_many :followers, through: :friendships, source: :user, dependent: :destroy
  has_many :followings, through: :friendships, source: :friend, dependent: :destroy

  # The "!" is a convention used to indicate that
  # the method will modify the object it's called on.
  # In other words, the method has a side effect.
  def like!(post)
    # In Ruby, the << operator is called the "append" or "concatenate" operator.
    # It is commonly used to add an element to the end of an array or a string.
    # this similar to self.likes
    likes << Like.new(post: post)
  end

  # Define a helper method to follow
  def follow!(user)
    # this similar to self.friendships
    unless friendships.exists?(friend_id: user.id)
        Friendship.create(user: user, friend: self)
    end
  end

  # Define a helper method to unfollow
  def unfollow!(user)
    Friendship.where(user: user, friend: self).delete_all
  end

  def followers_count
    Friendship.where(user_id: self.id).count
  end

  def followings_count
    Friendship.where(friend_id: self.id).count
  end
end

app/controllers/likes_controller.rb
# likes controller
class LikesController < ApplicationController
  before_action :require_login
  def create
    @post = Post.find(params[:post_id])
    current_user.like!(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    current_user.likes.where(post_id: @post.id).delete_all
  end
end

app/controllers/posts_controller.rb
# post controller
class PostsController < ApplicationController
  before_action :require_login
  # initialize new post object and send to view by @post
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.valid?
      @post.save
      respond_to do |format|
        format.html { redirect_to sites_path, notice: 'Post was successfully created.' }
        format.turbo_stream { flash.now[:notice] = 'Post was successfully created.' }
      end
      send_notification_to_friends(current_user, @post)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def post_params
    params.require(:post).permit(:body, :image)
  end
end

app/controllers/site_controller.rb
# itrepresents home page
class SiteController < ApplicationController
  # showing all post
  # TODO: only for user show the post otherwise show landing page
  def index
    # send the post form db to view by @posts
    @posts = Post.order(created_at: :desc)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def index
    @users = user_signed_in? ? User.all.where.not(id: current_user.id) :  User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_turbo_stream_flash_messages
    turbo_stream.prepend "flash", partial: "layouts/flash"
  end

  def form_error_notification(object)
    if object.errors.any?
      tag.div class: "alert alert-danger" do
        object.errors.full_messages.to_sentence.capitalize
      end
    end
  end

  def nested_dom_id(*args)
    args.map { |arg| arg.respond_to?(:to_key) ? dom_id(arg) : arg }.join("_")
  end
end

app/helpers/auths_helper.rb
# authentication and authorization functions
module AuthsHelper
  def require_login
    redirect_to new_user_session_path unless user_signed_in?
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
  def send_notification_to_friends(user, post)
    friend_ids = Friendship.where(user_id: user.id).pluck(:friend_id)
    User.where(id: friend_ids).each do |friend|
      NewsMailer.notification(friend, post).deliver_later
    end
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, message| %>
  <div
    class="alert alert-warning"
    >
    <%= message %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <%= link_to "Social Media", sites_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item me-5">
              <%= link_to "Members", users_path, class: "btn btn-primary" %>
          </li>
          <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete }, class: "btn btn-danger" %>
            <%= link_to user_path(current_user) do %>
              <%= image_tag(current_user.avatar.url, alt: 'avatar', class: "avatar-user") %>
            <% end %>
          </li>
          <% else %>
          <li class="nav-item">
            <%= link_to "Sign in", new_user_session_path, class: "btn btn-success" %>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_new_post_button.html.erb
 <% if user_signed_in? %>
      <%= turbo_frame_tag "post-form" do %>
      <div class="position-fixed bottom-0 end-0 p-3 m-4">
         <%= link_to "New post", new_post_path, class: "btn btn-dark btn-lg", data: { turbo_frame: dom_id(Post.new) } %>
      </div>
      <% end %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instaclone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= turbo_include_tags %>
    <%= javascript_importmap_tags %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "mystyle", "data-turbo-track": "reload" %>
  </head>

  <body >
   <%= render 'layouts/navbar'%>
    <%= render 'layouts/new_post_button'%>
     <%# handle flash messages %>
    <div id='flash' class='flash'>
      <%= render 'layouts/flash' %>
    </div>
     <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>